#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::RealBin/lib";

use Git::Lint;

my $lint = Git::Lint->new();
$lint->run();

if ( keys %{ $lint->{issues} } ) {
    print STDERR "the following issues were found:\n\n";

    foreach my $filename ( keys %{ $lint->{issues} } ) {
        print STDERR $filename . "\n";

        foreach my $issue ( @{ $lint->{issues}{$filename} } ) {
            print STDERR $issue . "\n";
        }

        print STDERR "\n";
    }

    exit 1;
}

exit 0;
